[package]
name = "dev-engineeringlabs-rustboot-uuid"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "UUID generation and validation"
keywords = ["uuid", "guid"]
categories = ["data-structures"]

[dependencies]
uuid = { workspace = true, features = ["v4", "v7"] }
thiserror = { workspace = true }
