[package]
name = "dev-engineeringlabs-rustboot-toolchain"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Development tooling and utilities"
keywords = ["tooling", "development", "utilities"]
categories = ["development-tools"]

[dependencies]
# Error handling
thiserror = { workspace = true }
